[package]
name = "hometex"
version = "0.1.0"
edition = "2021"
description = "A language that writes latex without writing latex"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nom = "7.1.3"
